# server:
#   ingress:
#     enabled: true
#     ## Prometheus server Ingress hostnames
#     ## Must be provided if Ingress is enabled
#     hosts:
#       - prometheus.eks.hanimao.com
#     tls:
#       - secretName: prometheus-server-tls
#         hosts:
#           - prometheus.eks.hanimao.com

 